name: Checkout-Job
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -lha
            - uses: actions/checkout@v3

            - name: List Files After
              run: ls -lha
              
           