name: First Workflow

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo a string
        run: echo "Hello World"

      - name: Multiline Command
        run: |
          node -v
          npm -v
