name: Pull Request Comment
on:
  pull_request_target:
    types: [opened]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on New Retes PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createCmment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issie.number
              body: 'Thanks for contributing!',
            });