name: Testing Secrets & Env Variables & Decrypting
on: [push]

jobs:
  decrypt-file:
    runs-on: ${{ vars.JOBS_RUNNER }}
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run:  |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/secret.json secret.json.gpg
      - name: View encrypted File Contents
        run: cat $HOME/secrets/secret.json

  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    environment: 'production'
    env: 
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "Congrats, I ran because I am true,"
      - name: Log Vars
        run:  |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"