name: Working Dir & Shells

on: [push]

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory & List Files
        shell: pwsh
        run: |
          Get-Location
          Get-ChildItem -Force
          Write-Output $env:GITHUB_SHA
          Write-Output $env:GITHUB_REPOSITORY
          Write-Output $env:GITHUB_WORKSPACE
